### ISSUE TITLE
Шаблон для Api на C#

### ISSUE THREAD

**Issue by litichevskiydv** [Byndyusoft/byndyusoft-templates-api#1]
Собрать шаблон Api, состоящий из следующих компонент:
- [x]  Пакет с трассировкой
- [x]  Пакет для логирования
- [x]  Пакет для доступа к данным
- [x]  Общая инфра для версионирования 
- [x]  Общая инфра для генерации swagger
- [x]  Настроена выдача метрик (время обработки запросов, их количество и коды ответа)
- [x]  Настроены health-пробы
- [x]  Мигратор
- [x]  Пакет с контрактами
- [x]  Пакет клиентом
- [x]  Интеграционные тесты на TestHost'е
- [x]  Сделать как шаблон

Добавить Readme с содержанием:
- [ ]  Информация о хелсчеках

**Comment by litichevskiydv** [comment]
Активные работы начнутся на 01.6

**Comment by litichevskiydv** [comment]
Сегодня будет оценка работ, после этого согласуем ее с Сашей

**Comment by kanybekov** [comment]
Пакет для доступа к данным требует версию пакета Microsoft.Extensions.DependencyInjection.Abstractions (>= 5.0.0)
Пакет с трассировкой зависит от OpenTracing.Contrib.NetCore, который зависит от Microsoft.Extensions.DependencyInjection.Abstractions (>= 3.1.8 && < 4.0.0)

После выставления версии 5.0.0, проект билдится, но отображается warning, что смущает.
Что делаем дальше?

**Comment by kanybekov** [comment]
В клиенте есть тудухи, обсужу с Антоном, что можно по ним сделать.

**Comment by litichevskiydv** [comment]
Все идет по плану

**Comment by kanybekov** [comment]
Для версионирования выбрали подход, когда информация о версии хранится в контейнере, в переменной окружения. Пакет логирования Ромы умеет подставлять в логи инфу из переменных окружения. Нужно договориться с девопсами, чтобы они клали ветку и коммит в переменные BUILD_BRANCH и BUILD_COMMIT.
Нужно убедиться, что трассировка подхватит информацию о версии из лога.

**Comment by kanybekov** [comment]
Обновить версию пакета трассировки, Ринат запилил новую фичу.

**Comment by litichevskiydv** [comment]
На следующей неделе закрываем два оставшихся пункта

**Comment by litichevskiydv** [comment]
Завтра планируем выпустить шаблончик

**Comment by Rinatich** [comment]
Создал ПР, скинул Ансару

**Comment by litichevskiydv** [comment]
Приложение готово и ждет исправления замечаний ревьвера, до конца недели будем устранять замечания. После этого засылаем PR на переделку репы в шаблон для dotnet.

**Comment by kanybekov** [comment]
Имхо, всё-таки нет смысла писать про хелсчеки в ридми. Это ничем не отличается от остальных фич, если чего-то не знаешь — идешь гуглить.

**Comment by litichevskiydv** [comment]
План действий:
1. Сливаем PR с функционалом
2. Сливаем PR с настройками публикации
3. Выпускаем preview-пакет
4. Собираем фидбек

**Comment by litichevskiydv** [comment]
Регистрируем мейнтейнеров и анонсируем кубик

**Comment by litichevskiydv** [comment]
Ансар 23.08 уточнит у Круглова, когда можно будет на денек уйти в разработку

**Comment by litichevskiydv** [comment]
Делаем локальный анонс и привлекаем новых пользователей

**Comment by litichevskiydv** [comment]
Анонс будет на следующей неделе к четвергу

**Comment by litichevskiydv** [comment]
На следующей неделе паблишим новую версию и делаем анонс в компании

**Comment by litichevskiydv** [comment]
Ждем @kanybekov до 04.10 чтобы сделать глобальный анонс

**Comment by litichevskiydv** [comment]
Добавляем R#, публикуем в NuGet и просим Ольгу выпустить пресс-релиз

**Comment by litichevskiydv** [comment]
@kanybekov готовит статью для ананоса к 20.10
