### ISSUE TITLE
Добавить документацию в шаблон API о том, как сдружить трассировки OpenTelemetry и JaegerTracing

### ISSUE THREAD

**Issue by Rinatich** [Byndyusoft/byndyusoft-templates-api#24]

**Comment by KillWolfVlad** [comment]
Ринат сделает анонс.

**Comment by litichevskiydv** [comment]
@govorovvs и @Rinatich  сделает внутренний анонс и расскажут про саму OpenTelemetry и нашу инструментацию

**Comment by litichevskiydv** [comment]
@Rinatich через неделю расскажет о практике использования новых инструментов

**Comment by litichevskiydv** [comment]
Ждем, когда кто-то попробует)

**Comment by litichevskiydv** [comment]
Создали сервис из нового шаблона, как раскатим - дадим фидбек

**Comment by litichevskiydv** [comment]
Ждем фидбека от Насти Шумаковой
