### ISSUE TITLE
Создать более информативное название пакета для шаблона сервиса

### ISSUE THREAD

**Issue by Rinatich** [Byndyusoft/byndyusoft-templates-api#30]
Сейчас сервис называется как Byndyusoft.Template, но не понятно, шаблон чего. Возможно, стоит сделать другое название пакета в nuget.org

**Comment by Rinatich** [comment]
Возможно, стоит назвать как Byndyusoft.Template.Api

**Comment by Rinatich** [comment]
Нужно посмотреть, как делают это Microsoft

**Comment by Alex-Grigorichev** [comment]
Рома апрувнул ПР, хочу подождать ещё хотя бы 1-2 апрува и сливать ПР.

**Comment by litichevskiydv** [comment]
Саша собирает Рому, Витю и Рината и фиксирует итоговое название

**Comment by Alex-Grigorichev** [comment]
Зафиксировали итоговое название: Byndyusoft.DotNet.Web.ProjectTemplate. ПР апрувнули Рома и Ринат, публикую новую версию пакета.
Ринат подсветил следующий момент: поскольку меняется название пакета, то старый нужно пометить как deprecated. Это можно сделать следующий способом: https://learn.microsoft.com/en-us/nuget/nuget-org/deprecate-packages
Также судя по этой статье можно перенести Popularity от старого пакета на новый.
